### ISSUE TITLE
Hi commarmi76

### ISSUE THREAD

**Issue by filipeaguiar22** [commarmi76/libopus_for_esp32#1]
Are you still developing the library?
I really would like to use the opus in the esp32 and I take my hat to your efforts of porting the library.

Filipe

**Comment by commarmi76** [comment]
Yes, but unfortunately I had no time to work to it last weeks.
I did the easiest part (compile, solve memory issues, etc..) , but I've got frustrated by the ogg part.
What are you looking for ? Play or encode opus files ?

Br.

**Comment by filipeaguiar22** [comment]
I am interested in encoding. Want to make it work with esp32 to reduce a
lot of space in portable equipment.

**Comment by commarmi76** [comment]
I worked in lame mp3 encore https://github.com/commarmi76/libmp3lame_for_esp32 aslo.
Coding the same file on a PC and my lame for esp32, I've got the same mp3 encoded file. Using only one esp32 core is it possible to encode 16KHz stereo file in less of realtime.
Obioussly I need to work in the optimization, but isn't the straightforward part.

**Comment by filipeaguiar22** [comment]
Indeed, optimization is not the trivial part... 
Thanks I will take a look.
Thanks for the reply
